In [2]:
print("Hello PYTHON")

Hello PYTHON

**Step 1 Data Exploration & Loading**

In [3]:
#importing dependencies
import pandas as pd
#mysql Toolkit
#pymysql # This will work as a adapter 
#sqlalchemy # This will work as a engine to connect to the database

#psql
#psycopg2 # This will work as a adapter

import pymysql as pm
from sqlalchemy import create_engine

import psycopg2
from sqlalchemy import create_engine

In [4]:
print(pd.__version__)

3.0.1

In [5]:
df = pd.read_csv('Walmart.csv', encoding_errors='ignore')

df.shape

(10051, 11)

In [6]:
df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,$74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,$15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,$46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,$58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,$86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [7]:
df.describe()

         invoice_id      quantity        rating  profit_margin
count  10051.000000  10020.000000  10051.000000   10051.000000
mean    5025.741220      2.353493      5.825659       0.393791
std     2901.174372      1.602658      1.763991       0.090669
min        1.000000      1.000000      3.000000       0.180000
25%     2513.500000      1.000000      4.000000       0.330000
50%     5026.000000      2.000000      6.000000       0.330000
75%     7538.500000      3.000000      7.000000       0.480000
max    10000.000000     10.000000     10.000000       0.570000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10051 entries, 0 to 10050
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      10051 non-null  int64
 1   Branch          10051 non-null  str
 2   City            10051 non-null  str
 3   category        10051 non-null  str
 4   unit_price      10020 non-null  str
 5   quantity        10020 non-null  float64
 6   date            10051 non-null  str
 7   time            10051 non-null  str
 8   payment_method  10051 non-null  str
 9   rating          10051 non-null  float64
 10  profit_margin   10051 non-null  float64
dtypes: float64(3), int64(1), str(7)
memory usage: 863.9 KB

In [9]:
df.duplicated().sum()

np.int64(51)

In [10]:
df.drop_duplicates(inplace=True)

df.duplicated().sum()

np.int64(0)

In [11]:
df.isnull().sum()

invoice_id         0
Branch             0
City               0
category           0
unit_price        31
quantity          31
date               0
time               0
payment_method     0
rating             0
profit_margin      0
dtype: int64

In [12]:
# Dropping all the rowa with null values
df.dropna(inplace=True)

df.isnull().sum()

invoice_id        0
Branch            0
City              0
category          0
unit_price        0
quantity          0
date              0
time              0
payment_method    0
rating            0
profit_margin     0
dtype: int64

In [13]:
df.shape

(9969, 11)

In [14]:
df['unit_price'] = df['unit_price'] = df['unit_price'].str.replace('$', '').astype(float)

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48

In [15]:
df.info()

<class 'pandas.DataFrame'>
Index: 9969 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_id      9969 non-null   int64
 1   Branch          9969 non-null   str
 2   City            9969 non-null   str
 3   category        9969 non-null   str
 4   unit_price      9969 non-null   float64
 5   quantity        9969 non-null   float64
 6   date            9969 non-null   str
 7   time            9969 non-null   str
 8   payment_method  9969 non-null   str
 9   rating          9969 non-null   float64
 10  profit_margin   9969 non-null   float64
dtypes: float64(4), int64(1), str(6)
memory usage: 934.6 KB

In [16]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin'],
      dtype='str')

In [17]:
df['total_sales'] = df['quantity'] * df['unit_price']

df.head()

,invoice_id,Branch,City,category,unit_price,quantity,date,time,payment_method,rating,profit_margin,total_sales
0,1,WALM003,San Antonio,Health and beauty,74.69,7.0,05/01/19,13:08:00,Ewallet,9.1,0.48,522.83
1,2,WALM048,Harlingen,Electronic accessories,15.28,5.0,08/03/19,10:29:00,Cash,9.6,0.48,76.40
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7.0,03/03/19,13:23:00,Credit card,7.4,0.33,324.31
3,4,WALM064,Bedford,Health and beauty,58.22,8.0,27/01/19,20:33:00,Ewallet,8.4,0.33,465.76
4,5,WALM013,Irving,Sports and travel,86.31,7.0,08/02/19,10:37:00,Ewallet,5.3,0.48,604.17

In [18]:
# mysql
# host = localhost
# user = root
# password = "password"

# psql
# host = localhost
# user = postgres
# password = "password"

In [19]:
df.shape

(9969, 12)

In [20]:
df.to_csv('Walmart_Cleaned.csv', index=False)

In [21]:
#  mysql connection

# engine_mysql = create_engine('mysql+pymysql://root:password@localhost:3306/walmart_sales')

# try:
#     engine_mysql
#     print("Connection to MySQL database successful!")
# except
#     print("Connection to MySQL database failed.")

In [22]:
#postgresql connection

engine_psql = create_engine('postgresql+psycopg2://postgres:Kovid%4019@localhost:5432/Walmart_Analysis_P8')
try:
    engine_psql
    print("Connection to PostgreSQL database successful!")
except:
    print("Connection to PostgreSQL database failed.")

Connection to PostgreSQL database successful!

In [23]:
df.to_sql(name='walmart', con=engine_psql, if_exists='append', index=False)

DatabaseError: Execution failed on sql 'INSERT INTO walmart (invoice_id, "Branch", "City", category, unit_price, quantity, date, time, payment_method, rating, profit_margin, total_sales) VALUES (:invoice_id, :Branch, :City, :category, :unit_price, :quantity, :date, :time, :payment_method, :rating, :profit_margin, :total_sales)': (psycopg2.errors.UndefinedColumn) column "Branch" of relation "walmart" does not exist
LINE 1: INSERT INTO walmart (invoice_id, "Branch", "City", category,...
                                         ^

[SQL: INSERT INTO walmart (invoice_id, "Branch", "City", category, unit_price, quantity, date, time, payment_method, rating, profit_margin, total_sales) VALUES (%(invoice_id__0)s, %(Branch__0)s, %(City__0)s, %(category__0)s, %(unit_price__0)s, %(quantity__ ... 230482 characters truncated ... time__999)s, %(payment_method__999)s, %(rating__999)s, %(profit_margin__999)s, %(total_sales__999)s)]
[parameters: {'total_sales__0': 522.8299999999999, 'City__0': 'San Antonio', 'quantity__0': 7.0, 'rating__0': 9.1, 'invoice_id__0': 1, 'unit_price__0': 74.69, 'date__0': '05/01/19', 'time__0': '13:08:00', 'profit_margin__0': 0.48, 'payment_method__0': 'Ewallet', 'Branch__0': 'WALM003', 'category__0': 'Health and beauty', 'total_sales__1': 76.39999999999999, 'City__1': 'Harlingen', 'quantity__1': 5.0, 'rating__1': 9.6, 'invoice_id__1': 2, 'unit_price__1': 15.28, 'date__1': '08/03/19', 'time__1': '10:29:00', 'profit_margin__1': 0.48, 'payment_method__1': 'Cash', 'Branch__1': 'WALM048', 'category__1': 'Electronic accessories', 'total_sales__2': 324.31, 'City__2': 'Haltom City', 'quantity__2': 7.0, 'rating__2': 7.4, 'invoice_id__2': 3, 'unit_price__2': 46.33, 'date__2': '03/03/19', 'time__2': '13:23:00', 'profit_margin__2': 0.33, 'payment_method__2': 'Credit card', 'Branch__2': 'WALM067', 'category__2': 'Home and lifestyle', 'total_sales__3': 465.76, 'City__3': 'Bedford', 'quantity__3': 8.0, 'rating__3': 8.4, 'invoice_id__3': 4, 'unit_price__3': 58.22, 'date__3': '27/01/19', 'time__3': '20:33:00', 'profit_margin__3': 0.33, 'payment_method__3': 'Ewallet', 'Branch__3': 'WALM064', 'category__3': 'Health and beauty', 'total_sales__4': 604.1700000000001, 'City__4': 'Irving' ... 11900 parameters truncated ... 'Branch__995': 'WALM012', 'category__995': 'Health and beauty', 'total_sales__996': 973.8, 'City__996': 'Fort Worth', 'quantity__996': 10.0, 'rating__996': 4.4, 'invoice_id__996': 997, 'unit_price__996': 97.38, 'date__996': '02/03/19', 'time__996': '17:16:00', 'profit_margin__996': 0.48, 'payment_method__996': 'Ewallet', 'Branch__996': 'WALM005', 'category__996': 'Home and lifestyle', 'total_sales__997': 31.84, 'City__997': 'Mission', 'quantity__997': 1.0, 'rating__997': 7.7, 'invoice_id__997': 998, 'unit_price__997': 31.84, 'date__997': '09/02/19', 'time__997': '13:22:00', 'profit_margin__997': 0.48, 'payment_method__997': 'Ewallet', 'Branch__997': 'WALM041', 'category__997': 'Food and beverages', 'total_sales__998': 65.82, 'City__998': 'Big Spring', 'quantity__998': 1.0, 'rating__998': 4.1, 'invoice_id__998': 999, 'unit_price__998': 65.82, 'date__998': '22/02/19', 'time__998': '15:33:00', 'profit_margin__998': 0.33, 'payment_method__998': 'Cash', 'Branch__998': 'WALM095', 'category__998': 'Home and lifestyle', 'total_sales__999': 618.38, 'City__999': 'Waco', 'quantity__999': 7.0, 'rating__999': 6.6, 'invoice_id__999': 1000, 'unit_price__999': 88.34, 'date__999': '18/02/19', 'time__999': '13:28:00', 'profit_margin__999': 0.48, 'payment_method__999': 'Cash', 'Branch__999': 'WALM025', 'category__999': 'Fashion accessories'}]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [ ]:
df.columns

Index(['invoice_id', 'Branch', 'City', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin',
       'total_sales'],
      dtype='str')

In [ ]:
df.columns = df.columns.str.lower()
df.columns

Index(['invoice_id', 'branch', 'city', 'category', 'unit_price', 'quantity',
       'date', 'time', 'payment_method', 'rating', 'profit_margin',
       'total_sales'],
      dtype='str')